apiVersion: cert-manager.io/v1alpha1
kind: Certificate'
metadata:
    name: k8s-multi-com-tls
spec:
    secretName: canopusstar-com
    issuerRef:
        name: letsencrypt-prod
        kind: CkusterIssuer
    commonName: canopusstar.com
    dnsNames:
        - canopusstar.com
        - www.canopusstar.com
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - canopusstar.com
                - www.canopusstar.com